apiVersion: v1
kind: Pod

metadata:
        name: mydb-pod
        namespace: kelnamespace
        labels:
                name: mydb-pod
                project: workshop2

spec:
        containers:
        - name: mydb-container
          image: stackupiss/northwind-db:v1
          imagePullPolicy: IfNotPresent 
          ports:
          - containerPort: 3306        
          env:
          - name: DB_HOST
            value: localhost
